spring:
    datasource:
      url: ENC(ujUYOm9RnzV+nxd/VPItxZS+1YbIkwqSMWcicCxhDDezgIPX8EYswUcuuShgcEA13e3Q7XGujIE=)
      username : ENC(g5gYia4h9g3THpuMbwqoVHEGif+LQpTw)
      password: ENC(IbmNAQwCG0lXRSZSpTObuA==)
      driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace




server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie

upload:
  path: D:/file/
