spring:
    datasource:
      url: ENC(QNo4FwIZvaMVSDORmxeTfVD5vL/njChkA94oc7B+3fG6GcvEetBTRQTc5J1CgKqP3z+WGnK+cxQ=)
      username : ENC(g5gYia4h9g3THpuMbwqoVHEGif+LQpTw)
      password: ENC(IbmNAQwCG0lXRSZSpTObuA==)
      driver-class-name: org.mariadb.jdbc.Driver


    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
    servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${PASSWORD}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace




server:
  servlet:
    session:
      timeout: 1800

upload:
  path: D:/file/
